name: Get Changed Directories

on:
  push:
    branches:
      - main  # Adjust the branch name as per your needs
  pull_request:
    branches:
      - main  # Adjust the branch name as per your needs

jobs:
  get_changed_dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v42

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          
